server:
  port: 8282
spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/authDB?createDatabaseIfNotExist=true
      username: postgres
      password: test123
      driver-class-name: org.postgresql.Driver
      initialization-mode: always
  #      initialization-mode: always
    jpa:
      hibernate:
        ddl-auto: create
      open-in-view: false
logging:
    level:
      org:
        hibernate:
          type: trace
#spring:
#  security:
#    user:
#      name: pathumw
#      password: test123
#      roles: ADMIN,USER
security:
  oauth2:
    client:
      client-id: mobile
      client-secret: pin
      access-token-validity-seconds: 3600
      authorized-grant-types: refresh_token,authorization_code,password,client_credentials
      scope: READ,WRITE