spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rentDB
    username: postgres
    password: test123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      dll-auto: create
      # naming:
      #   physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

