spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rentcloud_vehicle?createDatabaseIfNotExist=true
    username: postgres
    password: test123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create
  application:
    name: vehicle
server:
  port: 9191