spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rentcloud_customer?createDatabaseIfNotExist=true
    username: postgres
    password: test123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create
   # properties:
   #  hibernate:
   #   dialect: org.hibernate.dialect.MySQL55Dialect