server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/awpathum/Rent-a-car-project/tree/main/rent-a-car-service-config-store
          search-paths:
           - 'service-config/*service'
          #username: root
          #passphrase: 12345