server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/awpathum/Rent-a-car-project
          search-paths: '*'


#server:
#  port: 8191
#spring:
#  profiles:
#    active: native